In [33]:
import openai
import pandas as pd
import numpy as np
from getpass import getpass

openai.api_key = getpass()

 ········

In [34]:
df = pd.read_csv("words.csv")
df

            text
0            red
1       potatoes
2           soda
3         cheese
4          water
5           blue
6         crispy
7      hamburger
8         coffee
9          green
10          milk
11      la croix
12        yellow
13     chocolate
14  french fries
15         latte
16          cake
17         brown
18  cheeseburger
19      espresso
20    cheesecake
21         black
22         mocha
23         fizzy
24        carbon
25        banana

In [35]:
from openai.embeddings_utils import get_embedding

In [36]:
cappuccino = get_embedding("cappuccino", engine="text-embedding-ada-002")

In [37]:
df['embedding'] = df['text'].apply(lambda x: get_embedding(x, engine="text-embedding-ada-002"))
df.to_csv("word_embeddings.csv", index=False)

In [39]:
import ast

def list_of_float64(value):
    return np.array(ast.literal_eval(value), dtype=np.float64)

df = pd.read_csv("word_embeddings.csv", converters={"embedding": list_of_float64})
df

            text                                          embedding
0            red  [-6.423245940823108e-05, -0.024778805673122406...
1       potatoes  [0.004971202462911606, -0.031133046373724937, ...
2           soda  [0.025859493762254715, -0.007452284451574087, ...
3         cheese  [-0.0038699328433722258, -0.009271041490137577...
4          water  [0.019031280651688576, -0.01257743313908577, 0...
5           blue  [0.005434895399957895, -0.0072994716465473175,...
6         crispy  [-0.0010056837927550077, -0.005415474995970726...
7      hamburger  [-0.01317964494228363, -0.001876765862107277, ...
8         coffee  [-0.0007566261338070035, -0.0194522924721241, ...
9          green  [0.01538460049778223, -0.010931522585451603, 0...
10          milk  [0.0009238893981091678, -0.019352708011865616,...
11      la croix  [-0.012369148433208466, -0.011375079862773418,...
12        yellow  [0.007648157421499491, -0.024834953248500824, ...
13     chocolate  [0.0015507291536778212, -0.012970025651156902,...
14  french fries  [0.0014476682990789413, -0.016491735354065895,...
15         latte  [-0.015634099021553993, -0.003942839801311493,...
16          cake  [-0.013669422827661037, -0.016827937215566635,...
17         brown  [-0.003347564022988081, -0.015835314989089966,...
18  cheeseburger  [-0.018216600641608238, 0.005054354667663574, ...
19      espresso  [-0.02250584401190281, -0.012747502885758877, ...
20    cheesecake  [0.01136965025216341, -0.012745062820613384, -...
21         black  [-0.015190942212939262, -0.031228860840201378,...
22         mocha  [-0.012487593106925488, -0.026140518486499786,...
23         fizzy  [-0.013046763837337494, -0.010264534503221512,...
24        carbon  [0.004606652073562145, -0.025070752948522568, ...
25        banana  [-0.013975119218230247, -0.03290277719497681, ...

In [45]:
coca = get_embedding("coca-cola", engine="text-embedding-ada-002")

In [47]:
from openai.embeddings_utils import cosine_similarity
df["similarities"] = df["embedding"].apply(lambda x: cosine_similarity(x, cappuccino))
res = df.sort_values("similarities", ascending=False)
res

,text,embedding,similarities
19,espresso,"[-0.02250584401190281, -0.012747502885758877, ...",0.916526
15,latte,"[-0.015634099021553993, -0.003942839801311493,...",0.893022
22,mocha,"[-0.012487593106925488, -0.026140518486499786,...",0.877394
8,coffee,"[-0.0007566261338070035, -0.0194522924721241, ...",0.869637
10,milk,"[0.0009238893981091678, -0.019352708011865616,...",0.845948
13,chocolate,"[0.0015507291536778212, -0.012970025651156902,...",0.822439
3,cheese,"[-0.0038699328433722258, -0.009271041490137577...",0.810949
20,cheesecake,"[0.01136965025216341, -0.012745062820613384, -...",0.806181
7,hamburger,"[-0.01317964494228363, -0.001876765862107277, ...",0.802164
18,cheeseburger,"[-0.018216600641608238, 0.005054354667663574, ...",0.800163
2,soda,"[0.025859493762254715, -0.007452284451574087, ...",0.800020
23,fizzy,"[-0.013046763837337494, -0.010264534503221512,...",0.799841
16,cake,"[-0.013669422827661037, -0.016827937215566635,...",0.796994
14,french fries,"[0.0014476682990789413, -0.016491735354065895,...",0.793789
6,crispy,"[-0.0010056837927550077, -0.005415474995970726...",0.793281
25,banana,"[-0.013975119218230247, -0.03290277719497681, ...",0.790220
4,water,"[0.019031280651688576, -0.01257743313908577, 0...",0.786240
21,black,"[-0.015190942212939262, -0.031228860840201378,...",0.784345
1,potatoes,"[0.004971202462911606, -0.031133046373724937, ...",0.781386
17,brown,"[-0.003347564022988081, -0.015835314989089966,...",0.781319
0,red,"[-6.423245940823108e-05, -0.024778805673122406...",0.776750
9,green,"[0.01538460049778223, -0.010931522585451603, 0...",0.776621
12,yellow,"[0.007648157421499491, -0.024834953248500824, ...",0.776379
24,carbon,"[0.004606652073562145, -0.025070752948522568, ...",0.771219
5,blue,"[0.005434895399957895, -0.0072994716465473175,...",0.770851
11,la croix,"[-0.012369148433208466, -0.011375079862773418,...",0.766355